src/UI/Http/Web/Controller/AbstractController.php
<?php

declare(strict_types=1);

namespace Zentlix\MainBundle\UI\Http\Web\Controller;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBag;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Contracts\Translation\TranslatorInterface;
use Twig\Environment;

abstract class AbstractController implements AbstractControllerInterface
{
    public function __construct(
        protected HttpFoundation\RequestStack $requestStack,
        protected SerializerInterface $serializer,
        protected AuthorizationCheckerInterface $authorizationChecker,
        protected FormFactoryInterface $formFactory,
        protected ParameterBag $parameterBag,
        protected RouterInterface $router,
        protected TranslatorInterface $translator,
        protected Environment $twig,
        protected TokenStorageInterface $tokenStorage
    ) {
    }

    protected function redirect(string $url, int $status = 302): HttpFoundation\RedirectResponse
    {
        return new HttpFoundation\RedirectResponse($url, $status);
    }

    protected function redirectToRoute(
        string $route,
        array $parameters = [],
        int $status = 302
    ): HttpFoundation\RedirectResponse {
        return $this->redirect($this->router->generate($route, $parameters), $status);
    }

    protected function json(
        mixed $data,
        int $status = 200,
        array $headers = [],
        array $context = []
    ): HttpFoundation\JsonResponse {
        $json = $this->serializer->serialize($data, 'json', array_merge([
            'json_encode_options' => HttpFoundation\JsonResponse::DEFAULT_ENCODING_OPTIONS,
        ], $context));

        return new HttpFoundation\JsonResponse($json, $status, $headers, true);
    }

    protected function addFlash(string $type, mixed $message): void
    {
        try {
            $this->requestStack->getSession()->getFlashBag()->add($type, $message);
        } catch (HttpFoundation\Exception\SessionNotFoundException $e) {
            throw new \LogicException('You cannot use the addFlash method if sessions are disabled.', 0, $e);
        }
    }

    protected function renderView(string $view, array $parameters = []): string
    {
        return $this->twig->render($view, $parameters);
    }

    protected function render(
        string $view,
        array $parameters = [],
        HttpFoundation\Response $response = null
    ): HttpFoundation\Response {
        $content = $this->renderView($view, $parameters);

        if (null === $response) {
            $response = new HttpFoundation\Response();
        }

        $response->setContent($content);

        return $response;
    }

    protected function getUser(): ?UserInterface
    {
        if (null === $token = $this->tokenStorage->getToken()) {
            return null;
        }

        return $token->getUser();
    }
}

src/Resources/views/widgets/admin_panel.html.twig
<link href="{{ '/zentlix/main-bundle/assets/dist/admin.css' }}" rel="stylesheet">
<script src="{{ '/zentlix/main-bundle/assets/dist/admin.bundle.js' }}"></script>
<div class="zx-admin-panel">
    <div role="navigation">
        <ul>
            <li>
                <a href="{{ path('admin.index') }}"><i class="nav-icon icon-speedometer"></i> {{ 'zentlix_main.control_panel' | trans }}</a>
            </li>
            <li class="zx-sub-items">
                <a href="#"><i class="nav-icon icon-plus"></i> {{ 'zentlix_main.add' | trans }}</a>
                <div>
                    <ul>
                        <li><a href="{{ path('admin.user.create') }}">{{ 'zentlix_user.user.adm_panel_add' | trans }}</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <div class="zx-visual-editor">
        <div class="toggle-group">
            <input type="checkbox" name="zx-visual-editor" id="on-off-switch" {% if(isEnabledEditor) %} checked="" {% endif %} tabindex="1">
            <label for="on-off-switch">
                <span class="aural">{{ 'zentlix_main.editor' | trans }}</span> {{ 'zentlix_main.visual_editor' | trans }}
            </label>
            <div class="onoffswitch" aria-hidden="true">
                <div class="onoffswitch-label">
                    <div class="onoffswitch-inner"></div>
                    <div class="onoffswitch-switch"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="micromodal micromodal-slide" id="admin-modal" aria-hidden="true">
        <div class="micromodal__overlay" tabindex="-1" data-micromodal-close>
            <div class="micromodal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
                <header class="micromodal__header">
                    <h2 class="micromodal__title admin-panel-modal-title"></h2>
                    <button class="micromodal__close" aria-label="Close modal" data-micromodal-close></button>
                </header>
                <main class="micromodal__content admin-panel-modal-content"></main>
                <footer class="micromodal__footer">
                    <button class="micromodal__btn micromodal__btn-primary micromodal-submit">{{ 'zentlix_main.save' | trans }}</button>
                    <button class="micromodal__btn" data-micromodal-close aria-label="Close this dialog window">{{ 'zentlix_main.cancel' | trans }}</button>
                </footer>
            </div>
        </div>
    </div>
    <div class="micromodal micromodal-slide" id="admin-modal-error" aria-hidden="true">
        <div class="micromodal__overlay" tabindex="-1" data-micromodal-close>
            <div class="micromodal__container" role="dialog" aria-modal="true" aria-labelledby="modal-2-title">
                <header class="micromodal__header">
                    <h2 class="micromodal__title">{{ 'zentlix_main.error' | trans }}</h2>
                    <button class="micromodal__close" aria-label="Close modal" data-micromodal-close></button>
                </header>
                <main class="micromodal__content admin-panel-error-content"><div class="alert alert-warning" role="alert"></div>
                </main>
                <footer class="micromodal__footer">
                    <button class="micromodal__btn micromodal__btn-primary micromodal-submit" data-micromodal-close>{{ 'zentlix_main.close' | trans }}</button>
                </footer>
            </div>
        </div>
    </div>
</div>